In [ ]:
import re
text='Hello This is a Sample EMAIl to check MAnoj and RAM'
text_lower = text.lower()
print(text_lower)



hello this is a sample email to check manoj and ram


In [ ]:
import re
text='Hello This is a Sample EMAIl to check MAnoj and RAM'
text_clean = re.sub(r'[^a-z]',' ',text)
print(text_clean)

 ello  his is a  ample     l to check   noj and    


In [ ]:
import nltk
from nltk.corpus  import stopwords
nltk.download('stopwords',quiet=True)
stop_words=set(stopwords.words('english'))
text="I went a trip on monday"
tokens=[]
for word in text.split():
  if word not in stop_words:
    tokens.append(word)
print(tokens)

['I', 'went', 'trip', 'monday']


In [ ]:
import nltk
nltk.download('punkt_tab',quiet=True)
sentence="I don't love proposals ,do you?"
basic=sentence.split()
print('Basic split:',basic)
from nltk.tokenize import word_tokenize
smart =word_tokenize(sentence.lower())
print("NLTK tokenize:",smart)

Basic split: ['I', "don't", 'love', 'proposals', ',do', 'you?']
NLTK tokenize: ['i', 'do', "n't", 'love', 'proposals', ',', 'do', 'you', '?']


In [ ]:
import nltk
from nltk.stem import PorterStemmer,WordNetLemmatizer
nltk.download('wordnet',quiet=True)
stemmer = PorterStemmer()
lemmatizer=WordNetLemmatizer()
words = ['running','studies','better','caring','happily']
for word in words:
  stem = stemmer.stem(word)
  lemmatizer = lemmatizer.lemmatize(word)


In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer

nltk.download(['stopwords','wordnet','punkt'],quiet=True)
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

def preprocess(text):
   text=text.lower()

   text=re.sub(r'[^a-z]',' ',text)
   tokens=text.split()
   filtered_tokens =[]
   for w in tokens:
    if w not in stop_words:
      filtered_tokens.append(w)
   tokens=filtered_tokens

   lemmatized_tokens=[]
   for w in tokens:
    lemmatized_tokens.append(lemmatizer.lemmatize(w))
   tokens = lemmatized_tokens
   return ' '.join(tokens)
print(preprocess('I am walking towards the  nearest park to see the Visuals'))

walking towards nearest park see visuals


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
email={
    'cricket match cricket match ',
    'free win money free  win money',
    'cricket match free win money cricket'
}
cv=CountVectorizer()
x=cv.fit_transform(email).toarray()
print('vocabullary: ',cv.get_feature_names_out())
print(x)


vocabullary:  ['cricket' 'free' 'match' 'money' 'win']
[[0 2 0 2 2]
 [2 1 1 1 1]
 [2 0 2 0 0]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
email={
    'cricket match cricket match ',
    'free win money free  win money',
    'cricket match free win money cricket'
}
tfidf=TfidfVectorizer( sublinear_tf=True,max_df=0.95,min_df=1)
x=tfidf.fit_transform(email).toarray()
print('feature names: ',tfidf.get_feature_names_out())
print('tfidf matrix')
import numpy as np
print(np.round(x,3))


feature names:  ['cricket' 'free' 'match' 'money' 'win']
tfidf matrix
[[0.    0.577 0.    0.577 0.577]
 [0.646 0.382 0.382 0.382 0.382]
 [0.707 0.    0.707 0.    0.   ]]


Lab — Spam Email Classifier
Build a real spam detector using TF-IDF + Logistic Regression from scratch

In [ ]:
import pandas as pd
import numpy as np
!wget -q https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip
!unzip -o smsspamcollection.zip
!mv SMSSpamCollection SMSSpamCollection
df = pd.read_csv('SMSSpamCollection', sep='\t',
header=None, names=['label', 'message'])
# Quick look at the data
print(df.head())
print('\nShape:', df.shape) # (5574, 2)
print('\nClass balance:')
print(df['label'].value_counts()) # ham: 4827, spam: 747
print(f'Spam rate: {747/5574*100:.1f}%') # ~13% spam
# Check a spam example
print('\nSpam example:')
print(df[df['label']=='spam']['message'].iloc[0])
# 'Free entry in 2 a wkly comp to win FA Cup...'

Archive:  smsspamcollection.zip
  inflating: SMSSpamCollection       
  inflating: readme                  
mv: 'SMSSpamCollection' and 'SMSSpamCollection' are the same file
  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

Shape: (5572, 2)

Class balance:
label
ham     4825
spam     747
Name: count, dtype: int64
Spam rate: 13.4%

Spam example:
Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
